Add methods update parameters PoS
EYBlockchain/nightfall_3 pull request #1036
Opened 2022-09-30 23:21 UTC by daveroga

## What does this implement/fix? Explain your changes.
Feat: #1018 
Update parameters PoS.

## Does this close any currently open issues?
Issue #1018 

## What commands can I run to test the change? 
npm run test-administrator

## Any other comments?
No

2022-10-03 15:28 UTC, signorecello approved these changes

2022-10-04 21:17 UTC, druiz0992 requested changes
Can you update the doc/ folder to reflect the changes to the proposer?

2022-10-04 21:27 UTC, daveroga commented
> Can you update the doc/ folder to reflect the changes to the proposer?

Yes, of course. I'll do these changes. Thanks.

2022-10-06 09:41 UTC, pawelgrzybek approved these changes

2022-10-06 11:37 UTC, druiz0992 approved these changes

2022-10-06 11:37 UTC, merged