Removing transaction type
EYBlockchain/nightfall_3 pull request #1166
Opened 2022-10-27 15:56 UTC by RogerTaule

## What does this implement/fix? Explain your changes.
WIP
## Does this close any currently open issues?

## What commands can I run to test the change? 

## Any other comments?

2022-11-03 12:35 UTC, daveroga requested changes

2022-11-03 12:35 UTC, daveroga commented on nightfall-deployer/migrations/2_deploy_upgradeable.js
> +  await deployProxy(Shield, { deployer, unsafeAllowLinkedLibraries: true });
Why this change here and not in `Proposers` or `Challenges` about the empty parameters `[ ]`?

2022-11-03 12:35 UTC, daveroga commented on wallet/src/nightfall-browser/services/commitment-storage.js
> +      ? vals.filter(v => v.isNullified && v.isOnChain >= 0 && v.nullifierCircuitHash === '2')
Is this correct? It seems `v.nullifierCircuitHash` is a hash and won't be '2'.

2022-11-04 14:36 UTC, IlyasRidhuan commented on nightfall-optimist/src/routes/proposer.mjs
> +        fee: Number(fee),
This is an out of scope change for this PR - but this should be `BigInt` in the future if we are support > 64bit fees

2022-11-04 14:36 UTC, IlyasRidhuan commented on test/e2e/tokens/erc721.test.mjs
> +  describe.skip('Deposit', () => {
remove skip

2022-11-04 14:36 UTC, IlyasRidhuan commented on test/adversary/adversary-code/database.mjs
> +    const res = await db.collection(TRANSACTIONS_COLLECTION).find().toArray();
we will need to filter this for transactions that only have nullifiers for this test

2022-11-04 14:38 UTC, RogerTaule commented on config/default.js
> +      isWithdrawing: true,
Right, that's what happens when you copy paste xD

2022-11-04 16:18 UTC, merged