L2 Tokenisation
EYBlockchain/nightfall_3 pull request #1216
Opened 2022-11-11 16:45 UTC by RogerTaule

WIP

2022-11-15 15:45 UTC, imagobea reviewed
_Doncs molt be_ Tokenisation team! (ie well done) Hats off to you :tada: 

I just left some notes for myself and a very small number of suggestions where I've tagged Mr @RogerTaule 

Look fw to merge this and see how the "nightfall-node" implementation responds :crossed_fingers: Congrats again!!! :rocket:

2022-11-15 23:20 UTC, daveroga reviewed
First of all congrats for the amazing work done in this PR to all the team involved in the different parts and specially to @RogerTaule for the big effort in moving all the circuits to Circom and the different optimizations.

I only have left some comments to understand better some parts.

2022-11-18 10:07 UTC, signorecello requested changes
I can't even grasp the amount of work this is. Mad respect by the three of you that have written such good stuff

2022-11-18 10:07 UTC, signorecello commented on test/e2e/tokens/erc1155.test.mjs
> +    await emptyL2(nf3Users[0], web3Client, eventLogs);
Can we pass this as an object? `emptyL2({user: nf3Users[0], web3: web3Client, logs: eventLogs})` and destructure them on the other side? So it's easier to see what does the method expect without having to check the other file

2022-11-18 10:07 UTC, signorecello commented on README.md
> +  - Use `-r` to use ropsten node hosted by the dev team. Note: with option -r set environment
I think we don't have ropsten anymore?

2022-11-18 11:41 UTC, RogerTaule commented on nightfall-optimist/src/services/block-utils.mjs
> +export const packInfo = (blockNumberL2, leafCount, proposer) => {
We have different packing, one for the transaction structure and one for the block one. However, it is true that there was code duplicated, I'll try to remove it

2022-11-18 12:48 UTC, druiz0992 commented on docker/docker-compose.adversary.yml
> +      BLOCKCHAIN_WS_HOST: ${BLOCKCHAIN_WS_HOST:-blockchain}
We are using standalone.geth for some tests. I dont care if adversary uses ganache, but please dont remove the yml

2022-11-18 15:08 UTC, daveroga approved these changes

2022-11-18 18:42 UTC, merged