Westlad/x509 add real certs
EYBlockchain/nightfall_3 pull request #1407
Opened 2023-03-09 12:38 UTC by Westlad

## What does this implement/fix? Explain your changes.

This PR adds 'live' certificates for deployment on Polygon PoS

## What commands can I run to test the change? 

There is a new unit test which checks that `X509.sol` can correclty parse the new certificates.

2023-03-26 13:08 UTC, israelboudoux requested changes
Just a few things to verify.

2023-03-27 08:40 UTC, Westlad commented on nightfall-deployer/contracts/X509.sol
> +    // allows a key to be revoked by signing the originating address (useful for intermediate certs)
No, it's actually intended to be used by the owner of the key, in the event of a key compromise. I'll improve the comment though as it's certainly not clear.

2023-03-27 08:42 UTC, Westlad commented on nightfall-deployer/contracts/X509.sol
> +    function revokeKeyByAddressSignature(
That's correct.  It doesn't need to be just a CA though, it can also be used by the owner of an end-user cert.

2023-03-27 16:00 UTC, israelboudoux approved these changes

2023-03-28 07:09 UTC, druiz0992 approved these changes

2023-03-28 07:10 UTC, merged