remove PARALLEL_SETUP logic in nightfall_deployer
EYBlockchain/nightfall_3 pull request #1419
Opened 2023-04-17 22:51 UTC by LijuJoseJJ

## What does this implement/fix? Explain your changes.
this PR removes parallel execution of contract deploy and circuit setup

2023-04-18 07:28 UTC, druiz0992 approved these changes

2023-04-18 15:36 UTC, Westlad requested changes
This code attempts the deployment twice, once in the `deployContracts` function in the `index.mjs` of `nightfall-deployer` and once in `nightfall-deployer`'s `entrypoint.sh`.  This is evidenced by the double compile. Please removed one or the other.

2023-04-19 03:09 UTC, LijuJoseJJ commented
> This code attempts the deployment twice, once in the `deployContracts` function in the `index.mjs` of `nightfall-deployer` and once in `nightfall-deployer`'s `entrypoint.sh`. This is evidenced by the double compile. Please removed one or the other.

removed

2023-04-19 09:34 UTC, Westlad approved these changes

2023-04-19 09:35 UTC, merged