Hari/idle proposers
EYBlockchain/nightfall_3 pull request #162
Opened 2021-09-17 08:19 UTC by dwebchapey

partial fix on idle proposers issue #96 

Consider following  following scenario 
```
Block1             Block2            Block3            Current proposer
proposerA    ->    proposerB   ->    proposerC    ->    proposerD
Good Block         Bad Block         Good block         Yet to publish
```
If at this point Block2 is challenged and Rolled-back, all of proposerCs' blocks will be deleted. When proposerB is removed, the order of propers will be proposerA -> proposerC -> proposerD. 

This will enable proposerD to challenge that proposerC was idle, when in reality the Rollback made it appear so.

Inorder to get control of this scenario , the proposer state can also be rolled up corresponding to the last genuine block , in this case , Block 1, proposer A . The current proposer will be set to block after Block1 proposer , which is proposer C now (proposer B is removed after roll back ) .  

in `Challenges.sol>Challenges>challengeAccepted()` function , we perform 3 operations

1. emitRollback
2. removeBlockHashes
3. rewardChallenger

In `rewardChallenger` we call `removeProposer` where we recreate the proposers list after delinking bad proposer and also doing a check that if removed proposer is 'currentProposer'  , we set the proposer to next address.  In this fix , we set the `currentProposer` as next address irrespective of current state of proposer list.

```

  function removeProposer(address proposer) public onlyRegistered {
    address previousAddress = proposers[proposer].previousAddress;
    address nextAddress = proposers[proposer].nextAddress;
    delete proposers[proposer];
    proposers[previousAddress].nextAddress = proposers[nextAddress].thisAddress;
    proposers[nextAddress].previousAddress = proposers[previousAddress].thisAddress;
   //change currentProposer to next aaddress irrespective of whether bad proposer is currentProposer
   // if(proposer == currentProposer.thisAddress) {
      // Cannot just call changeCurrentProposer directly due to the require time check
      proposerStartBlock = block.number;
      currentProposer = proposers[nextAddress];
      emit NewCurrentProposer(currentProposer.thisAddress);
   // }
  }

```

This would reset the state of both L2 blocks and proposer list to pre rollup state with current proposer set as next addr of latest genuine L2 proposer.

Points to ponder

- In above example , if a rollback at B happen when D is current proposer , the new proposer will be C . This can be argued since D is made to wait further to be proposer due to no fault of its own . But the hypothesis is that since C's blocks were also 'unfairly' slashed from chain , it would be fair to reset the counter to C. 

- Scenario when rollback will be beneficial for a newly joined proposer since they could be picked sooner
Eg :  If a new proposer E join right while C is current proposer it will added to back of the queue , the new proposer list will be 

A <-> _**B <-> E <-> C**_ <-> D  

After B is rolled back , proposer E gets to be current proposer instead of proposer C which gives unfair advantage to E over C.

2021-09-17 08:40 UTC, IlyasRidhuan requested changes

2021-09-17 08:40 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +    }
nit: we don't have a linter running on `.sol` files but this white space should be removed

2021-09-17 08:40 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/State.sol
> +   // if(proposer == currentProposer.thisAddress) {
Delete the code instead of just commenting it out. As much as we can comments should be reserved for actual comments.

2021-09-20 09:05 UTC, Westlad approved these changes

2021-09-20 09:06 UTC, merged