David/wallet withdraw
EYBlockchain/nightfall_3 pull request #389
Opened 2021-12-27 17:38 UTC by druiz0992

Better withdrawal processing. Click on `Withdrawal Information` button to get an overview of remaining withdrawals. You can either finalize pending withdrawals or request an instant withdraw.

2022-01-21 10:04 UTC, ChaitanyaKonda commented on doc/lib/nf3.mjs.html
> +    const res = await axios.post(`${this.clientBaseUrl}/commitment/balance`);
Updating to `GET`.

Probably a rebase with the ERC1155 branch will update this automatically.

2022-01-21 17:50 UTC, ChaitanyaKonda requested changes
This PR should be rebased with the latest master.
The changes from ERC1155 PR don't reflect here

2022-01-27 08:02 UTC, druiz0992 commented
Merge with master done. Ready to review

2022-02-01 09:53 UTC, daveroga approved these changes

2022-02-04 10:59 UTC, closed without merging