PoS integration
EYBlockchain/nightfall_3 pull request #506
Opened 2022-02-16 15:21 UTC by daveroga

Fixes #474 , #475, #488 

This PR integrates Proof of Stake into Nightfall following the proposal in #283

2022-02-24 09:39 UTC, signorecello requested changes

2022-02-25 17:20 UTC, daveroga commented on cli/src/proposer.mjs
> +  await nf3.stakeProposer(1000);
Yes. I'll push now changes with a parameter for starting the proposer with `--stake <amount>`

2022-02-28 07:01 UTC, daveroga commented on nightfall-deployer/contracts/State.sol
> +  function shuffleSlots() internal {
We can change randomness for shuffling slots with Chainlink VRF functionality. But this is a decision that will introduce the need of having LINK tokens and makes them available to fund requests to Chainlink VRF coordinators.

2022-02-28 09:19 UTC, signorecello commented on nightfall-deployer/contracts/State.sol
> +  function shuffleSlots() internal {
I believe both would be good solutions for different stages of project maturity. In either case I wouldn't use a timestamp...

2022-02-28 19:12 UTC, ChaitanyaKonda commented
Since we will be reviewing this when we are ready to have POS merged into master, can we close this PR which merges `daveroga/pos-proposal-integration2` into `feature-pos` and open a new PR when we want to merge `feature-pos` into `master` ? Until then we will have this as the branch `feature-pos`.

Otherwise, this would be sitting in pending PRs until ready for review which would be sometime until mainnet launch.

2022-03-01 18:49 UTC, merged