feat: scripts for MPC + removing MPC from the worker process 🔨
EYBlockchain/nightfall_3 pull request #633
Opened 2022-04-28 15:13 UTC by signorecello

2022-04-29 05:29 UTC, druiz0992 requested changes
I would like to have some instructions on how to run this MPC in the main README section

2022-04-29 05:29 UTC, druiz0992 commented on MPC/contribution.js
> +
If you print the input randomness, you will see it does not match what you entered.

2022-04-29 05:29 UTC, druiz0992 commented on MPC/mpc_contribute.sh
> +docker build -t contribute --build-arg NAME=${NAME} --build-arg RANDOM=${RANDOM} .
Add "${NAME}" and "${RANDOM}" instead. Otherwise, it will fail if one enters a space as one of the characters

2022-05-03 13:41 UTC, Westlad approved these changes

2022-05-04 08:00 UTC, signorecello commented
For clarity, the MPC ceremony has been moved to a new repo, here: https://github.com/maticnetwork/nightfall_phase2ceremony

2022-05-04 09:27 UTC, merged