zokrates upgraded to 0.7.13
EYBlockchain/nightfall_3 pull request #774
Opened 2022-06-27 21:36 UTC by LijuJoseJJ

this PR upgrade  zokrates version from 0.7.10 to 0.7.13.
also do a small refactor to zokrates.Dockerfile

2022-08-01 11:16 UTC, LijuJoseJJ commented
Now this PR also fix zokrates-js version to 1.0.43 from 1.0.41 for wallet.
since wallet is not working 1.0.43 is not properly tested.

2022-08-01 13:42 UTC, IlyasRidhuan requested changes

2022-08-01 13:42 UTC, IlyasRidhuan commented on zokrates.Dockerfile
> -RUN rustup toolchain install nightly
I think you still need this for M1 Macs

2022-08-01 15:07 UTC, LijuJoseJJ commented on zokrates.Dockerfile
> -RUN rustup toolchain install nightly
added back

2022-08-07 11:51 UTC, IlyasRidhuan approved these changes

2022-08-07 11:51 UTC, merged