feat: adding ack to block produced websocket 🔌
EYBlockchain/nightfall_3 pull request #795
Opened 2022-07-05 11:23 UTC by signorecello

It implements a basic ```ack``` response when nf3 receives and signs a block. This is not a very extensive implementation so I wouldn't really close #665 for now. In order to close it, I would think of refactoring using rabbitmq or sockets.io or any other tools that give us better reliability, while providing us analytics and other data management tools.

The optimist will attempt to broadcast the block every 10 seconds, three times, if it doesn't get the ```ack``` from the optimist.

2022-07-05 11:51 UTC, druiz0992 requested changes
We plan to use this in several places (proposer, challenger...). Can we include the functionality in a library in common-files maybe and just show in block proposer how to use it?

2022-07-08 10:11 UTC, daveroga commented on cli/lib/nf3.mjs
> +    this.rabbitmq.subscribe({ queue: 'block' }, message => {
Here it seems it should subscribe to `challenge` instead `block`

2022-07-08 10:12 UTC, daveroga commented on cli/lib/nf3.mjs
> +    this.rabbitmq.subscribe({ queue: 'block' }, message => {
Good approach though with rabbitmq

2022-07-09 10:19 UTC, signorecello commented
I started looking into rabbitmq here, then after talking with @druiz0992 we decided to move that to another (draft) PR. I'll try to close this one asap

2022-07-18 08:20 UTC, daveroga approved these changes
Well organized now with some of the common functions in common-files :)

2022-07-18 08:20 UTC, daveroga approved these changes
Well organized now with some of the common functions in common-files :)

2022-08-02 06:05 UTC, druiz0992 approved these changes

2022-08-02 06:05 UTC, merged