Stuffing ping-pong in a mocha test
EYBlockchain/nightfall_3 pull request #823
Opened 2022-07-20 15:31 UTC by signorecello

I'm cherry-picking some leftovers from the (then dropped) PR about mock contracts.

This PR proposes that ping-pong tests are made into a mocha test so it's easier and faster to run, develop, debug, etc

2022-07-24 12:12 UTC, israelboudoux approved these changes
LGTM, nice cleaning btw, this will require me to change my stuff related to the Ping-Pong test that I'm doing for Jenkins, but it is for the better.

2022-07-26 12:25 UTC, Westlad approved these changes

2022-08-03 21:36 UTC, druiz0992 requested changes
Changes in this PR affect how the proposer is launched in private repo. Before merging this PR, private repo needs to work correctly

2022-08-25 19:27 UTC, signorecello commented
I finally was able to make the change on the deployment repo (uff), so I'm requesting re-review

2022-09-11 10:16 UTC, druiz0992 approved these changes

2022-09-11 12:15 UTC, merged