Save block proposed time in transactions
EYBlockchain/nightfall_3 pull request #829
Opened 2022-07-27 07:12 UTC by daveroga

Fixes: #828 

- Add time of block proposed to transactions in optimist (`timeBlockL2`)

2022-07-27 21:26 UTC, druiz0992 requested changes
- Why can’t you add block-info.mjs to common files and avoid duplication?
- Can you add time stamp to block as well?

2022-07-28 00:46 UTC, daveroga commented
> * Why can’t you add block-info.mjs to common files and avoid duplication?
> * Can you add time stamp to block as well?

Yes, did it but didn't pushed it yet. Now both points are done.

2022-07-28 13:18 UTC, druiz0992 approved these changes

2022-07-29 09:22 UTC, Westlad approved these changes

2022-07-29 09:22 UTC, merged