bigint constants refactored from config
EYBlockchain/nightfall_3 pull request #879
Opened 2022-08-16 14:16 UTC by LijuJoseJJ

2022-08-25 08:50 UTC, israelboudoux commented
Hey @LijuJoseJJ, could you solve the merge conflicts please?

2022-09-11 13:29 UTC, pawelgrzybek requested changes

2022-09-11 13:29 UTC, pawelgrzybek commented on common-files/constants/bigInts.js
> +BigInt.prototype.toJSON = function () {
Looks like we don't use this `toJSON` at all in the codebase. Good time to get rid of it.

2022-09-15 13:23 UTC, pawelgrzybek commented on common-files/constants/bigInts.js
> +BigInt.prototype.toJSON = function () {
I already spoke about it with @IlyasRidhuan, this comment is not relevant anymore. Sorry

2022-09-19 06:52 UTC, RogerTaule approved these changes
LGTM

2022-09-19 09:02 UTC, signorecello approved these changes
LGTM

2022-09-19 09:04 UTC, merged