Roger taule/leaf count modification
EYBlockchain/nightfall_3 pull request #917
Opened 2022-09-12 08:22 UTC by RogerTaule

This PR adds a series of optimizations for the current challenges. It does the following changes:

- leafCount is no longer the amount of commitments in the merkle tree before insertion. With this change, leafCount is now the amount of commitments **after** insertion.
- The siblingPath info is stored for the transactions merkle tree.
- The whole set of transactions contained in a block is no longer sent as part of the calldata in challengeDuplicateNullifier and challengeDuplicateCommitment. Instead, we verify that the transaction is real by verifying its sibling path.
- For the challengeProofVerification, there's no need of sending the whole transactions contained in a block. We just need to check that the historicBlock is real. A new function that only validates the block is created in State.sol to do that. 
- The way check-block was detecting duplicated commitments / nullifiers was outdated since it was relying in the fact that each transaction has two commits and two nullifiers, which is no longer true. The corresponding functions has been fixed.
- Transaction checker does no longer check for duplicate nullifiers or commitments in the same transaction, since this is no possible because the circuits will not allow it. Hence, it makes no sense checking it.

2022-09-16 11:44 UTC, israelboudoux requested changes
Hello @RogerTaule, would you mind add some unit tests re this change please?
Thank you!

2022-09-22 09:27 UTC, IlyasRidhuan requested changes

2022-09-22 09:27 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +            transaction1.blockL2.blockNumberL2 != transaction2.blockL2.blockNumberL2,
I don't think this is correct - this would make duplicate commitments in different transactions but in the same block un-challengeable.

2022-09-22 09:27 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +            transaction1.blockL2.blockNumberL2 != transaction2.blockL2.blockNumberL2,
The requirement if both transactions are in the same block is that they don't point to the same transaction (i.e. txIndex1 != txIndex2)

2022-09-22 09:27 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +            transaction1.blockL2.blockNumberL2 != transaction2.blockL2.blockNumberL2,
Same here as for commitment

2022-09-22 09:27 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +        if (uint256(transaction.transaction.nullifiers[0]) != 0) {
Can this sequence of checks just be compressed into a `for loop` that goes to `nullifiers.length`

2022-09-22 09:27 UTC, IlyasRidhuan commented on nightfall-deployer/contracts/Challenges.sol
> +    function challengeHistoricRoot(TransactionInfoBlock calldata transaction)
I know this wasn't part of the PR, but can we change this to `challengeHistoricRootBlockNumber` - there  might a reference that has to be updated in `optimist`

2022-09-23 10:56 UTC, IlyasRidhuan approved these changes

2022-09-23 16:29 UTC, israelboudoux approved these changes

2022-09-23 16:31 UTC, merged